// Code generated by dgdao-gen. DO NOT EDIT.

package movies

import (
	"context"
	"iter"
	"slices"

	"github.com/dgraph-io/dgdao"
	"github.com/dgraph-io/dgdao/typed"
	"github.com/dgraph-io/dgdao/typed/filter"

	"github.com/dgraph-io/dgdao-gen/cmd/dgdao-gen/internal/parser/testdata/movies/schema"
)

// Country wraps a schema.Country record and exposes its data through
// methods. It embeds dgdao.Entity, which supplies Record, JSON marshaling,
// and validation; the backing record struct is reachable only via Record().
type Country struct {
	dgdao.Entity[schema.Country]
}

// NewCountry constructs a Country with a fresh, empty record struct, then
// applies the given options.
func NewCountry(opts ...typed.Option[Country]) *Country {
	e := &Country{Entity: dgdao.AsEntity(&schema.Country{})}
	typed.Apply(e, opts...)
	return e
}

// NewCountryWithRecord constructs a Country backed by the given record
// struct, then applies the given options. The entity adopts r directly — no
// defensive copy, so setters mutate the caller's struct.
func NewCountryWithRecord(r *schema.Country, opts ...typed.Option[Country]) *Country {
	e := &Country{Entity: dgdao.AsEntity(r)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Country) UID() string { return e.Record().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Country) SetUID(v string) { e.Record().UID = v }

// DType returns the entity's dgraph type list.
func (e *Country) DType() []string { return e.Record().DType }

// SetDType sets the entity's dgraph type list.
func (e *Country) SetDType(v []string) { e.Record().DType = v }

// Name returns the name field.
func (e *Country) Name() string { return e.Record().Name }

// SetName sets the name field.
func (e *Country) SetName(v string) { e.Record().Name = v }

// Films returns a freshly allocated slice of entities over each
// Film in the multi-edge.
func (e *Country) Films() []*Film {
	out := make([]*Film, len(e.Record().Films))
	for i, x := range e.Record().Films {
		out[i] = &Film{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// FilmsSeq returns an iterator over the Film entities, avoiding
// the allocation in Films().
func (e *Country) FilmsSeq() iter.Seq[*Film] {
	return func(yield func(*Film) bool) {
		for _, x := range e.Record().Films {
			if !yield(&Film{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetFilms replaces the multi-edge with the given items.
func (e *Country) SetFilms(items ...*Film) {
	e.Record().Films = make([]*schema.Film, len(items))
	for i, x := range items {
		e.Record().Films[i] = x.Record()
	}
}

// AppendFilms appends items to the multi-edge.
func (e *Country) AppendFilms(items ...*Film) {
	for _, x := range items {
		e.Record().Films = append(e.Record().Films, x.Record())
	}
}

// RemoveFilms removes elements with any of the given UIDs from the multi-edge.
func (e *Country) RemoveFilms(uids ...string) {
	e.Record().Films = slices.DeleteFunc(e.Record().Films, func(x *schema.Film) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// WithCountryName sets the name field on a *Country.
func WithCountryName(v string) typed.Option[Country] {
	return func(e *Country) { e.SetName(v) }
}

// WithCountryFilms replaces the films multi-edge on a *Country
// with the given items.
func WithCountryFilms(items ...*Film) typed.Option[Country] {
	return func(e *Country) { e.SetFilms(items...) }
}

// CountryClient provides CRUD/query operations over Country entity values.
// It composes over a typed.Client bound to the record struct: reads wrap the
// record result, writes forward the entity's backing record.
type CountryClient struct {
	typed *typed.Client[schema.Country]
}

// NewCountryClient binds a CountryClient to conn — the connection client or
// a transaction-scoped *dgdao.ClientTxn.
func NewCountryClient(conn dgdao.ClientCore) *CountryClient {
	return &CountryClient{typed: typed.NewClient[schema.Country](conn)}
}

// InTxn returns a CountryClient whose reads and writes run within tx: reads
// join tx's read-set, writes stage on tx and land only on tx.Commit.
func (c *CountryClient) InTxn(tx *dgdao.Txn) *CountryClient {
	return &CountryClient{typed: c.typed.InTxn(tx)}
}

// Get loads the Country with the given UID and returns it wrapped.
func (c *CountryClient) Get(ctx context.Context, uid string) (*Country, error) {
	r, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return NewCountryWithRecord(r), nil
}

// Insert inserts the record struct backing e.
func (c *CountryClient) Insert(ctx context.Context, e *Country) error {
	return c.typed.Insert(ctx, e.Record())
}

// Update modifies the record struct backing e (must have UID set).
func (c *CountryClient) Update(ctx context.Context, e *Country) error {
	return c.typed.Update(ctx, e.Record())
}

// Upsert inserts or updates the record struct backing e, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *CountryClient) Upsert(ctx context.Context, e *Country, predicates ...string) error {
	return c.typed.Upsert(ctx, e.Record(), predicates...)
}

// Delete removes the Country with the given UID.
func (c *CountryClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns an entity-side query builder for Country.
func (c *CountryClient) Query(ctx context.Context) *CountryQuery {
	return &CountryQuery{typed: c.typed.Query(ctx)}
}

// QueryRaw executes a raw DQL query with optional variables on the backing
// conn. On a transaction-scoped client the query reads within the
// transaction (read-your-writes).
func (c *CountryClient) QueryRaw(ctx context.Context, q string, vars map[string]string) ([]byte, error) {
	return c.typed.QueryRaw(ctx, q, vars)
}

// FulltextFields returns the DQL predicate names of Country fields tagged
// with a "fulltext" index, in struct declaration order. Consumers iterate
// this list to build cross-field fulltext queries (e.g. typed.MultiQuery
// search) without hardcoding the field set; adding or removing a fulltext
// tag in the schema flows through on next `make generate`.
func (c *CountryClient) FulltextFields() []string {
	return []string{
		"name",
	}
}

// CountryQuery is the wrapper-side fluent query builder for Country. Builder
// methods return *CountryQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type CountryQuery struct {
	typed *typed.Query[schema.Country]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *CountryQuery) Filter(filter string, params ...any) *CountryQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *CountryQuery) OrderAsc(clause string) *CountryQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *CountryQuery) OrderDesc(clause string) *CountryQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *CountryQuery) Limit(n int) *CountryQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *CountryQuery) Offset(n int) *CountryQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *CountryQuery) After(uid string) *CountryQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *CountryQuery) Cascade(predicates ...string) *CountryQuery {
	q.typed.Cascade(predicates...)
	return q
}

// WhereFilms keeps only Country records that have a ~country
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *CountryQuery) WhereFilms(filter string, params ...any) *CountryQuery {
	q.typed.WhereEdge("~country", filter, params...)
	return q
}

// WhereFilmsBy keeps only Country records that have a ~country
// edge whose target node matches the filter composed inside build — a typed
// FilmQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereFilms: no
// hand-written DQL or $N placeholders.
func (q *CountryQuery) WhereFilmsBy(build func(*FilmQuery)) *CountryQuery {
	sub := &FilmQuery{typed: typed.NewDetachedQuery[schema.Film]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("~country", expr, params...)
	}
	return q
}

// ByName keeps only Country records whose name matches one
// of filters. Terms within filters join with OR. Negated filters (Negated:true) become
// NOT eq(...). An empty filters slice is a no-op.
func (q *CountryQuery) ByName(filters ...filter.String) *CountryQuery {
	var b filter.Builder
	b.EqGroupString("name", filters)
	if expr, params := b.Build(); expr != "" {
		q.typed.Filter(expr, params...)
	}
	return q
}

// Or keeps only Country records matching at least one of builders. Each builder
// receives a fresh CountryQuery whose By<Field>/Filter calls accumulate (ANDing
// within the builder); the builders' filters are ORed together and the whole
// group ANDs with the rest of the query. Builders that add no filter are
// skipped; an empty Or is a no-op.
func (q *CountryQuery) Or(builders ...func(*CountryQuery)) *CountryQuery {
	subs := make([]*typed.Query[schema.Country], 0, len(builders))
	for _, build := range builders {
		sub := &CountryQuery{typed: typed.NewDetachedQuery[schema.Country]()}
		build(sub)
		subs = append(subs, sub.typed)
	}
	q.typed.OrGroup(subs...)
	return q
}

// Nodes executes the query and returns the Country entities.
func (q *CountryQuery) Nodes() ([]*Country, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Country, len(recs))
	for i := range recs {
		out[i] = NewCountryWithRecord(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// Country entity, or nil if no rows matched.
func (q *CountryQuery) First() (*Country, error) {
	r, err := q.typed.First()
	if err != nil || r == nil {
		return nil, err
	}
	return NewCountryWithRecord(r), nil
}

// IterNodes streams the query's results as Country entities, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *CountryQuery) IterNodes() iter.Seq2[*Country, error] {
	return func(yield func(*Country, error) bool) {
		for r, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(NewCountryWithRecord(r), nil) {
				return
			}
		}
	}
}
