// Code generated by dgdao-gen. DO NOT EDIT.

package movies

import (
	"context"
	"iter"
	"slices"

	"github.com/dgraph-io/dgdao"
	"github.com/dgraph-io/dgdao/typed"
	"github.com/dgraph-io/dgdao/typed/filter"

	"github.com/dgraph-io/dgdao-gen/cmd/dgdao-gen/internal/parser/testdata/movies/schema"
)

// Director wraps a schema.Director record and exposes its data through
// methods. It embeds dgdao.Entity, which supplies Record, JSON marshaling,
// and validation; the backing record struct is reachable only via Record().
type Director struct {
	dgdao.Entity[schema.Director]
}

// NewDirector constructs a Director with a fresh, empty record struct, then
// applies the given options.
func NewDirector(opts ...typed.Option[Director]) *Director {
	e := &Director{Entity: dgdao.AsEntity(&schema.Director{})}
	typed.Apply(e, opts...)
	return e
}

// NewDirectorWithRecord constructs a Director backed by the given record
// struct, then applies the given options. The entity adopts r directly — no
// defensive copy, so setters mutate the caller's struct.
func NewDirectorWithRecord(r *schema.Director, opts ...typed.Option[Director]) *Director {
	e := &Director{Entity: dgdao.AsEntity(r)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Director) UID() string { return e.Record().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Director) SetUID(v string) { e.Record().UID = v }

// DType returns the entity's dgraph type list.
func (e *Director) DType() []string { return e.Record().DType }

// SetDType sets the entity's dgraph type list.
func (e *Director) SetDType(v []string) { e.Record().DType = v }

// Name returns the name field.
func (e *Director) Name() string { return e.Record().Name }

// SetName sets the name field.
func (e *Director) SetName(v string) { e.Record().Name = v }

// Films returns a freshly allocated slice of entities over each
// Film in the multi-edge.
func (e *Director) Films() []*Film {
	out := make([]*Film, len(e.Record().Films))
	for i, x := range e.Record().Films {
		out[i] = &Film{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// FilmsSeq returns an iterator over the Film entities, avoiding
// the allocation in Films().
func (e *Director) FilmsSeq() iter.Seq[*Film] {
	return func(yield func(*Film) bool) {
		for _, x := range e.Record().Films {
			if !yield(&Film{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetFilms replaces the multi-edge with the given items.
func (e *Director) SetFilms(items ...*Film) {
	e.Record().Films = make([]*schema.Film, len(items))
	for i, x := range items {
		e.Record().Films[i] = x.Record()
	}
}

// AppendFilms appends items to the multi-edge.
func (e *Director) AppendFilms(items ...*Film) {
	for _, x := range items {
		e.Record().Films = append(e.Record().Films, x.Record())
	}
}

// RemoveFilms removes elements with any of the given UIDs from the multi-edge.
func (e *Director) RemoveFilms(uids ...string) {
	e.Record().Films = slices.DeleteFunc(e.Record().Films, func(x *schema.Film) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// WithDirectorName sets the name field on a *Director.
func WithDirectorName(v string) typed.Option[Director] {
	return func(e *Director) { e.SetName(v) }
}

// WithDirectorFilms replaces the films multi-edge on a *Director
// with the given items.
func WithDirectorFilms(items ...*Film) typed.Option[Director] {
	return func(e *Director) { e.SetFilms(items...) }
}

// DirectorClient provides CRUD/query operations over Director entity values.
// It composes over a typed.Client bound to the record struct: reads wrap the
// record result, writes forward the entity's backing record.
type DirectorClient struct {
	typed *typed.Client[schema.Director]
}

// NewDirectorClient binds a DirectorClient to conn — the connection client or
// a transaction-scoped *dgdao.ClientTxn.
func NewDirectorClient(conn dgdao.ClientCore) *DirectorClient {
	return &DirectorClient{typed: typed.NewClient[schema.Director](conn)}
}

// InTxn returns a DirectorClient whose reads and writes run within tx: reads
// join tx's read-set, writes stage on tx and land only on tx.Commit.
func (c *DirectorClient) InTxn(tx *dgdao.Txn) *DirectorClient {
	return &DirectorClient{typed: c.typed.InTxn(tx)}
}

// Get loads the Director with the given UID and returns it wrapped.
func (c *DirectorClient) Get(ctx context.Context, uid string) (*Director, error) {
	r, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return NewDirectorWithRecord(r), nil
}

// Insert inserts the record struct backing e.
func (c *DirectorClient) Insert(ctx context.Context, e *Director) error {
	return c.typed.Insert(ctx, e.Record())
}

// Update modifies the record struct backing e (must have UID set).
func (c *DirectorClient) Update(ctx context.Context, e *Director) error {
	return c.typed.Update(ctx, e.Record())
}

// Upsert inserts or updates the record struct backing e, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *DirectorClient) Upsert(ctx context.Context, e *Director, predicates ...string) error {
	return c.typed.Upsert(ctx, e.Record(), predicates...)
}

// Delete removes the Director with the given UID.
func (c *DirectorClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns an entity-side query builder for Director.
func (c *DirectorClient) Query(ctx context.Context) *DirectorQuery {
	return &DirectorQuery{typed: c.typed.Query(ctx)}
}

// QueryRaw executes a raw DQL query with optional variables on the backing
// conn. On a transaction-scoped client the query reads within the
// transaction (read-your-writes).
func (c *DirectorClient) QueryRaw(ctx context.Context, q string, vars map[string]string) ([]byte, error) {
	return c.typed.QueryRaw(ctx, q, vars)
}

// FulltextFields returns the DQL predicate names of Director fields tagged
// with a "fulltext" index, in struct declaration order. Consumers iterate
// this list to build cross-field fulltext queries (e.g. typed.MultiQuery
// search) without hardcoding the field set; adding or removing a fulltext
// tag in the schema flows through on next `make generate`.
func (c *DirectorClient) FulltextFields() []string {
	return []string{
		"name",
	}
}

// DirectorQuery is the wrapper-side fluent query builder for Director. Builder
// methods return *DirectorQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type DirectorQuery struct {
	typed *typed.Query[schema.Director]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *DirectorQuery) Filter(filter string, params ...any) *DirectorQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *DirectorQuery) OrderAsc(clause string) *DirectorQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *DirectorQuery) OrderDesc(clause string) *DirectorQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *DirectorQuery) Limit(n int) *DirectorQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *DirectorQuery) Offset(n int) *DirectorQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *DirectorQuery) After(uid string) *DirectorQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *DirectorQuery) Cascade(predicates ...string) *DirectorQuery {
	q.typed.Cascade(predicates...)
	return q
}

// WhereFilms keeps only Director records that have a director.film
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *DirectorQuery) WhereFilms(filter string, params ...any) *DirectorQuery {
	q.typed.WhereEdge("director.film", filter, params...)
	return q
}

// WhereFilmsBy keeps only Director records that have a director.film
// edge whose target node matches the filter composed inside build — a typed
// FilmQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereFilms: no
// hand-written DQL or $N placeholders.
func (q *DirectorQuery) WhereFilmsBy(build func(*FilmQuery)) *DirectorQuery {
	sub := &FilmQuery{typed: typed.NewDetachedQuery[schema.Film]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("director.film", expr, params...)
	}
	return q
}

// ByName keeps only Director records whose name matches one
// of filters. Terms within filters join with OR. Negated filters (Negated:true) become
// NOT eq(...). An empty filters slice is a no-op.
func (q *DirectorQuery) ByName(filters ...filter.String) *DirectorQuery {
	var b filter.Builder
	b.EqGroupString("name", filters)
	if expr, params := b.Build(); expr != "" {
		q.typed.Filter(expr, params...)
	}
	return q
}

// Or keeps only Director records matching at least one of builders. Each builder
// receives a fresh DirectorQuery whose By<Field>/Filter calls accumulate (ANDing
// within the builder); the builders' filters are ORed together and the whole
// group ANDs with the rest of the query. Builders that add no filter are
// skipped; an empty Or is a no-op.
func (q *DirectorQuery) Or(builders ...func(*DirectorQuery)) *DirectorQuery {
	subs := make([]*typed.Query[schema.Director], 0, len(builders))
	for _, build := range builders {
		sub := &DirectorQuery{typed: typed.NewDetachedQuery[schema.Director]()}
		build(sub)
		subs = append(subs, sub.typed)
	}
	q.typed.OrGroup(subs...)
	return q
}

// Nodes executes the query and returns the Director entities.
func (q *DirectorQuery) Nodes() ([]*Director, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Director, len(recs))
	for i := range recs {
		out[i] = NewDirectorWithRecord(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// Director entity, or nil if no rows matched.
func (q *DirectorQuery) First() (*Director, error) {
	r, err := q.typed.First()
	if err != nil || r == nil {
		return nil, err
	}
	return NewDirectorWithRecord(r), nil
}

// IterNodes streams the query's results as Director entities, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *DirectorQuery) IterNodes() iter.Seq2[*Director, error] {
	return func(yield func(*Director, error) bool) {
		for r, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(NewDirectorWithRecord(r), nil) {
				return
			}
		}
	}
}
