// Code generated by dgdao-gen. DO NOT EDIT.

package movies

import (
	"context"
	"iter"
	"slices"
	"time"

	"github.com/dgraph-io/dgdao"
	"github.com/dgraph-io/dgdao/typed"
	"github.com/dgraph-io/dgdao/typed/filter"

	"github.com/dgraph-io/dgdao-gen/cmd/dgdao-gen/internal/parser/testdata/movies/schema"
)

// Film wraps a schema.Film record and exposes its data through
// methods. It embeds dgdao.Entity, which supplies Record, JSON marshaling,
// and validation; the backing record struct is reachable only via Record().
type Film struct {
	dgdao.Entity[schema.Film]
}

// NewFilm constructs a Film with a fresh, empty record struct, then
// applies the given options.
func NewFilm(opts ...typed.Option[Film]) *Film {
	e := &Film{Entity: dgdao.AsEntity(&schema.Film{})}
	typed.Apply(e, opts...)
	return e
}

// NewFilmWithRecord constructs a Film backed by the given record
// struct, then applies the given options. The entity adopts r directly — no
// defensive copy, so setters mutate the caller's struct.
func NewFilmWithRecord(r *schema.Film, opts ...typed.Option[Film]) *Film {
	e := &Film{Entity: dgdao.AsEntity(r)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Film) UID() string { return e.Record().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Film) SetUID(v string) { e.Record().UID = v }

// DType returns the entity's dgraph type list.
func (e *Film) DType() []string { return e.Record().DType }

// SetDType sets the entity's dgraph type list.
func (e *Film) SetDType(v []string) { e.Record().DType = v }

// Name returns the name field.
func (e *Film) Name() string { return e.Record().Name }

// SetName sets the name field.
func (e *Film) SetName(v string) { e.Record().Name = v }

// InitialReleaseDate returns the initialReleaseDate field.
func (e *Film) InitialReleaseDate() time.Time { return e.Record().InitialReleaseDate }

// SetInitialReleaseDate sets the initialReleaseDate field.
func (e *Film) SetInitialReleaseDate(v time.Time) { e.Record().InitialReleaseDate = v }

// Tagline returns the tagline field.
func (e *Film) Tagline() string { return e.Record().Tagline }

// SetTagline sets the tagline field.
func (e *Film) SetTagline(v string) { e.Record().Tagline = v }

// Genres returns a freshly allocated slice of entities over each
// Genre in the multi-edge.
func (e *Film) Genres() []*Genre {
	out := make([]*Genre, len(e.Record().Genres))
	for i, x := range e.Record().Genres {
		out[i] = &Genre{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// GenresSeq returns an iterator over the Genre entities, avoiding
// the allocation in Genres().
func (e *Film) GenresSeq() iter.Seq[*Genre] {
	return func(yield func(*Genre) bool) {
		for _, x := range e.Record().Genres {
			if !yield(&Genre{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetGenres replaces the multi-edge with the given items.
func (e *Film) SetGenres(items ...*Genre) {
	e.Record().Genres = make([]*schema.Genre, len(items))
	for i, x := range items {
		e.Record().Genres[i] = x.Record()
	}
}

// AppendGenres appends items to the multi-edge.
func (e *Film) AppendGenres(items ...*Genre) {
	for _, x := range items {
		e.Record().Genres = append(e.Record().Genres, x.Record())
	}
}

// RemoveGenres removes elements with any of the given UIDs from the multi-edge.
func (e *Film) RemoveGenres(uids ...string) {
	e.Record().Genres = slices.DeleteFunc(e.Record().Genres, func(x *schema.Genre) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Countries returns a freshly allocated slice of entities over each
// Country in the multi-edge.
func (e *Film) Countries() []*Country {
	out := make([]*Country, len(e.Record().Countries))
	for i, x := range e.Record().Countries {
		out[i] = &Country{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// CountriesSeq returns an iterator over the Country entities, avoiding
// the allocation in Countries().
func (e *Film) CountriesSeq() iter.Seq[*Country] {
	return func(yield func(*Country) bool) {
		for _, x := range e.Record().Countries {
			if !yield(&Country{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetCountries replaces the multi-edge with the given items.
func (e *Film) SetCountries(items ...*Country) {
	e.Record().Countries = make([]*schema.Country, len(items))
	for i, x := range items {
		e.Record().Countries[i] = x.Record()
	}
}

// AppendCountries appends items to the multi-edge.
func (e *Film) AppendCountries(items ...*Country) {
	for _, x := range items {
		e.Record().Countries = append(e.Record().Countries, x.Record())
	}
}

// RemoveCountries removes elements with any of the given UIDs from the multi-edge.
func (e *Film) RemoveCountries(uids ...string) {
	e.Record().Countries = slices.DeleteFunc(e.Record().Countries, func(x *schema.Country) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Ratings returns a freshly allocated slice of entities over each
// Rating in the multi-edge.
func (e *Film) Ratings() []*Rating {
	out := make([]*Rating, len(e.Record().Ratings))
	for i, x := range e.Record().Ratings {
		out[i] = &Rating{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// RatingsSeq returns an iterator over the Rating entities, avoiding
// the allocation in Ratings().
func (e *Film) RatingsSeq() iter.Seq[*Rating] {
	return func(yield func(*Rating) bool) {
		for _, x := range e.Record().Ratings {
			if !yield(&Rating{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetRatings replaces the multi-edge with the given items.
func (e *Film) SetRatings(items ...*Rating) {
	e.Record().Ratings = make([]*schema.Rating, len(items))
	for i, x := range items {
		e.Record().Ratings[i] = x.Record()
	}
}

// AppendRatings appends items to the multi-edge.
func (e *Film) AppendRatings(items ...*Rating) {
	for _, x := range items {
		e.Record().Ratings = append(e.Record().Ratings, x.Record())
	}
}

// RemoveRatings removes elements with any of the given UIDs from the multi-edge.
func (e *Film) RemoveRatings(uids ...string) {
	e.Record().Ratings = slices.DeleteFunc(e.Record().Ratings, func(x *schema.Rating) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// ContentRatings returns a freshly allocated slice of entities over each
// ContentRating in the multi-edge.
func (e *Film) ContentRatings() []*ContentRating {
	out := make([]*ContentRating, len(e.Record().ContentRatings))
	for i, x := range e.Record().ContentRatings {
		out[i] = &ContentRating{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// ContentRatingsSeq returns an iterator over the ContentRating entities, avoiding
// the allocation in ContentRatings().
func (e *Film) ContentRatingsSeq() iter.Seq[*ContentRating] {
	return func(yield func(*ContentRating) bool) {
		for _, x := range e.Record().ContentRatings {
			if !yield(&ContentRating{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetContentRatings replaces the multi-edge with the given items.
func (e *Film) SetContentRatings(items ...*ContentRating) {
	e.Record().ContentRatings = make([]*schema.ContentRating, len(items))
	for i, x := range items {
		e.Record().ContentRatings[i] = x.Record()
	}
}

// AppendContentRatings appends items to the multi-edge.
func (e *Film) AppendContentRatings(items ...*ContentRating) {
	for _, x := range items {
		e.Record().ContentRatings = append(e.Record().ContentRatings, x.Record())
	}
}

// RemoveContentRatings removes elements with any of the given UIDs from the multi-edge.
func (e *Film) RemoveContentRatings(uids ...string) {
	e.Record().ContentRatings = slices.DeleteFunc(e.Record().ContentRatings, func(x *schema.ContentRating) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Starring returns a freshly allocated slice of entities over each
// Performance in the multi-edge.
func (e *Film) Starring() []*Performance {
	out := make([]*Performance, len(e.Record().Starring))
	for i, x := range e.Record().Starring {
		out[i] = &Performance{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// StarringSeq returns an iterator over the Performance entities, avoiding
// the allocation in Starring().
func (e *Film) StarringSeq() iter.Seq[*Performance] {
	return func(yield func(*Performance) bool) {
		for _, x := range e.Record().Starring {
			if !yield(&Performance{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetStarring replaces the multi-edge with the given items.
func (e *Film) SetStarring(items ...*Performance) {
	e.Record().Starring = make([]*schema.Performance, len(items))
	for i, x := range items {
		e.Record().Starring[i] = x.Record()
	}
}

// AppendStarring appends items to the multi-edge.
func (e *Film) AppendStarring(items ...*Performance) {
	for _, x := range items {
		e.Record().Starring = append(e.Record().Starring, x.Record())
	}
}

// RemoveStarring removes elements with any of the given UIDs from the multi-edge.
func (e *Film) RemoveStarring(uids ...string) {
	e.Record().Starring = slices.DeleteFunc(e.Record().Starring, func(x *schema.Performance) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Directors returns a freshly allocated slice of entities over each
// Director in the multi-edge.
func (e *Film) Directors() []*Director {
	out := make([]*Director, len(e.Record().Directors))
	for i, x := range e.Record().Directors {
		out[i] = &Director{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// DirectorsSeq returns an iterator over the Director entities, avoiding
// the allocation in Directors().
func (e *Film) DirectorsSeq() iter.Seq[*Director] {
	return func(yield func(*Director) bool) {
		for _, x := range e.Record().Directors {
			if !yield(&Director{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetDirectors replaces the multi-edge with the given items.
func (e *Film) SetDirectors(items ...*Director) {
	e.Record().Directors = make([]*schema.Director, len(items))
	for i, x := range items {
		e.Record().Directors[i] = x.Record()
	}
}

// AppendDirectors appends items to the multi-edge.
func (e *Film) AppendDirectors(items ...*Director) {
	for _, x := range items {
		e.Record().Directors = append(e.Record().Directors, x.Record())
	}
}

// RemoveDirectors removes elements with any of the given UIDs from the multi-edge.
func (e *Film) RemoveDirectors(uids ...string) {
	e.Record().Directors = slices.DeleteFunc(e.Record().Directors, func(x *schema.Director) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// WithFilmName sets the name field on a *Film.
func WithFilmName(v string) typed.Option[Film] {
	return func(e *Film) { e.SetName(v) }
}

// WithFilmInitialReleaseDate sets the initialReleaseDate field on a *Film.
func WithFilmInitialReleaseDate(v time.Time) typed.Option[Film] {
	return func(e *Film) { e.SetInitialReleaseDate(v) }
}

// WithFilmTagline sets the tagline field on a *Film.
func WithFilmTagline(v string) typed.Option[Film] {
	return func(e *Film) { e.SetTagline(v) }
}

// WithFilmGenres replaces the genres multi-edge on a *Film
// with the given items.
func WithFilmGenres(items ...*Genre) typed.Option[Film] {
	return func(e *Film) { e.SetGenres(items...) }
}

// WithFilmCountries replaces the countries multi-edge on a *Film
// with the given items.
func WithFilmCountries(items ...*Country) typed.Option[Film] {
	return func(e *Film) { e.SetCountries(items...) }
}

// WithFilmRatings replaces the ratings multi-edge on a *Film
// with the given items.
func WithFilmRatings(items ...*Rating) typed.Option[Film] {
	return func(e *Film) { e.SetRatings(items...) }
}

// WithFilmContentRatings replaces the contentRatings multi-edge on a *Film
// with the given items.
func WithFilmContentRatings(items ...*ContentRating) typed.Option[Film] {
	return func(e *Film) { e.SetContentRatings(items...) }
}

// WithFilmStarring replaces the starring multi-edge on a *Film
// with the given items.
func WithFilmStarring(items ...*Performance) typed.Option[Film] {
	return func(e *Film) { e.SetStarring(items...) }
}

// WithFilmDirectors replaces the directors multi-edge on a *Film
// with the given items.
func WithFilmDirectors(items ...*Director) typed.Option[Film] {
	return func(e *Film) { e.SetDirectors(items...) }
}

// FilmClient provides CRUD/query operations over Film entity values.
// It composes over a typed.Client bound to the record struct: reads wrap the
// record result, writes forward the entity's backing record.
type FilmClient struct {
	typed *typed.Client[schema.Film]
}

// NewFilmClient binds a FilmClient to conn — the connection client or
// a transaction-scoped *dgdao.ClientTxn.
func NewFilmClient(conn dgdao.ClientCore) *FilmClient {
	return &FilmClient{typed: typed.NewClient[schema.Film](conn)}
}

// InTxn returns a FilmClient whose reads and writes run within tx: reads
// join tx's read-set, writes stage on tx and land only on tx.Commit.
func (c *FilmClient) InTxn(tx *dgdao.Txn) *FilmClient {
	return &FilmClient{typed: c.typed.InTxn(tx)}
}

// Get loads the Film with the given UID and returns it wrapped.
func (c *FilmClient) Get(ctx context.Context, uid string) (*Film, error) {
	r, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return NewFilmWithRecord(r), nil
}

// Insert inserts the record struct backing e.
func (c *FilmClient) Insert(ctx context.Context, e *Film) error {
	return c.typed.Insert(ctx, e.Record())
}

// Update modifies the record struct backing e (must have UID set).
func (c *FilmClient) Update(ctx context.Context, e *Film) error {
	return c.typed.Update(ctx, e.Record())
}

// Upsert inserts or updates the record struct backing e, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *FilmClient) Upsert(ctx context.Context, e *Film, predicates ...string) error {
	return c.typed.Upsert(ctx, e.Record(), predicates...)
}

// Delete removes the Film with the given UID.
func (c *FilmClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns an entity-side query builder for Film.
func (c *FilmClient) Query(ctx context.Context) *FilmQuery {
	return &FilmQuery{typed: c.typed.Query(ctx)}
}

// QueryRaw executes a raw DQL query with optional variables on the backing
// conn. On a transaction-scoped client the query reads within the
// transaction (read-your-writes).
func (c *FilmClient) QueryRaw(ctx context.Context, q string, vars map[string]string) ([]byte, error) {
	return c.typed.QueryRaw(ctx, q, vars)
}

// FulltextFields returns the DQL predicate names of Film fields tagged
// with a "fulltext" index, in struct declaration order. Consumers iterate
// this list to build cross-field fulltext queries (e.g. typed.MultiQuery
// search) without hardcoding the field set; adding or removing a fulltext
// tag in the schema flows through on next `make generate`.
func (c *FilmClient) FulltextFields() []string {
	return []string{
		"name",
	}
}

// FilmQuery is the wrapper-side fluent query builder for Film. Builder
// methods return *FilmQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type FilmQuery struct {
	typed *typed.Query[schema.Film]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *FilmQuery) Filter(filter string, params ...any) *FilmQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *FilmQuery) OrderAsc(clause string) *FilmQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *FilmQuery) OrderDesc(clause string) *FilmQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *FilmQuery) Limit(n int) *FilmQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *FilmQuery) Offset(n int) *FilmQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *FilmQuery) After(uid string) *FilmQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *FilmQuery) Cascade(predicates ...string) *FilmQuery {
	q.typed.Cascade(predicates...)
	return q
}

// WhereGenres keeps only Film records that have a genre
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereGenres(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("genre", filter, params...)
	return q
}

// WhereGenresBy keeps only Film records that have a genre
// edge whose target node matches the filter composed inside build — a typed
// GenreQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereGenres: no
// hand-written DQL or $N placeholders.
func (q *FilmQuery) WhereGenresBy(build func(*GenreQuery)) *FilmQuery {
	sub := &GenreQuery{typed: typed.NewDetachedQuery[schema.Genre]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("genre", expr, params...)
	}
	return q
}

// WhereCountries keeps only Film records that have a country
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereCountries(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("country", filter, params...)
	return q
}

// WhereCountriesBy keeps only Film records that have a country
// edge whose target node matches the filter composed inside build — a typed
// CountryQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereCountries: no
// hand-written DQL or $N placeholders.
func (q *FilmQuery) WhereCountriesBy(build func(*CountryQuery)) *FilmQuery {
	sub := &CountryQuery{typed: typed.NewDetachedQuery[schema.Country]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("country", expr, params...)
	}
	return q
}

// WhereRatings keeps only Film records that have a rating
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereRatings(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("rating", filter, params...)
	return q
}

// WhereRatingsBy keeps only Film records that have a rating
// edge whose target node matches the filter composed inside build — a typed
// RatingQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereRatings: no
// hand-written DQL or $N placeholders.
func (q *FilmQuery) WhereRatingsBy(build func(*RatingQuery)) *FilmQuery {
	sub := &RatingQuery{typed: typed.NewDetachedQuery[schema.Rating]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("rating", expr, params...)
	}
	return q
}

// WhereContentRatings keeps only Film records that have a rated
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereContentRatings(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("rated", filter, params...)
	return q
}

// WhereContentRatingsBy keeps only Film records that have a rated
// edge whose target node matches the filter composed inside build — a typed
// ContentRatingQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereContentRatings: no
// hand-written DQL or $N placeholders.
func (q *FilmQuery) WhereContentRatingsBy(build func(*ContentRatingQuery)) *FilmQuery {
	sub := &ContentRatingQuery{typed: typed.NewDetachedQuery[schema.ContentRating]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("rated", expr, params...)
	}
	return q
}

// WhereStarring keeps only Film records that have a starring
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereStarring(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("starring", filter, params...)
	return q
}

// WhereStarringBy keeps only Film records that have a starring
// edge whose target node matches the filter composed inside build — a typed
// PerformanceQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereStarring: no
// hand-written DQL or $N placeholders.
func (q *FilmQuery) WhereStarringBy(build func(*PerformanceQuery)) *FilmQuery {
	sub := &PerformanceQuery{typed: typed.NewDetachedQuery[schema.Performance]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("starring", expr, params...)
	}
	return q
}

// WhereDirectors keeps only Film records that have a directors
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereDirectors(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("directors", filter, params...)
	return q
}

// WhereDirectorsBy keeps only Film records that have a directors
// edge whose target node matches the filter composed inside build — a typed
// DirectorQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereDirectors: no
// hand-written DQL or $N placeholders.
func (q *FilmQuery) WhereDirectorsBy(build func(*DirectorQuery)) *FilmQuery {
	sub := &DirectorQuery{typed: typed.NewDetachedQuery[schema.Director]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("directors", expr, params...)
	}
	return q
}

// ByName keeps only Film records whose name matches one
// of filters. Terms within filters join with OR. Negated filters (Negated:true) become
// NOT eq(...). An empty filters slice is a no-op.
func (q *FilmQuery) ByName(filters ...filter.String) *FilmQuery {
	var b filter.Builder
	b.EqGroupString("name", filters)
	if expr, params := b.Build(); expr != "" {
		q.typed.Filter(expr, params...)
	}
	return q
}

// Or keeps only Film records matching at least one of builders. Each builder
// receives a fresh FilmQuery whose By<Field>/Filter calls accumulate (ANDing
// within the builder); the builders' filters are ORed together and the whole
// group ANDs with the rest of the query. Builders that add no filter are
// skipped; an empty Or is a no-op.
func (q *FilmQuery) Or(builders ...func(*FilmQuery)) *FilmQuery {
	subs := make([]*typed.Query[schema.Film], 0, len(builders))
	for _, build := range builders {
		sub := &FilmQuery{typed: typed.NewDetachedQuery[schema.Film]()}
		build(sub)
		subs = append(subs, sub.typed)
	}
	q.typed.OrGroup(subs...)
	return q
}

// Nodes executes the query and returns the Film entities.
func (q *FilmQuery) Nodes() ([]*Film, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Film, len(recs))
	for i := range recs {
		out[i] = NewFilmWithRecord(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// Film entity, or nil if no rows matched.
func (q *FilmQuery) First() (*Film, error) {
	r, err := q.typed.First()
	if err != nil || r == nil {
		return nil, err
	}
	return NewFilmWithRecord(r), nil
}

// IterNodes streams the query's results as Film entities, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *FilmQuery) IterNodes() iter.Seq2[*Film, error] {
	return func(yield func(*Film, error) bool) {
		for r, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(NewFilmWithRecord(r), nil) {
				return
			}
		}
	}
}
