// Code generated by dgdao-gen. DO NOT EDIT.

package movies

import (
	"context"
	"iter"
	"slices"

	"github.com/dgraph-io/dgdao"
	"github.com/dgraph-io/dgdao/typed"
	"github.com/dgraph-io/dgdao/typed/filter"

	"github.com/dgraph-io/dgdao-gen/cmd/dgdao-gen/internal/parser/testdata/movies/schema"
)

// Genre wraps a schema.Genre record and exposes its data through
// methods. It embeds dgdao.Entity, which supplies Record, JSON marshaling,
// and validation; the backing record struct is reachable only via Record().
type Genre struct {
	dgdao.Entity[schema.Genre]
}

// NewGenre constructs a Genre with a fresh, empty record struct, then
// applies the given options.
func NewGenre(opts ...typed.Option[Genre]) *Genre {
	e := &Genre{Entity: dgdao.AsEntity(&schema.Genre{})}
	typed.Apply(e, opts...)
	return e
}

// NewGenreWithRecord constructs a Genre backed by the given record
// struct, then applies the given options. The entity adopts r directly — no
// defensive copy, so setters mutate the caller's struct.
func NewGenreWithRecord(r *schema.Genre, opts ...typed.Option[Genre]) *Genre {
	e := &Genre{Entity: dgdao.AsEntity(r)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Genre) UID() string { return e.Record().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Genre) SetUID(v string) { e.Record().UID = v }

// DType returns the entity's dgraph type list.
func (e *Genre) DType() []string { return e.Record().DType }

// SetDType sets the entity's dgraph type list.
func (e *Genre) SetDType(v []string) { e.Record().DType = v }

// Name returns the name field.
func (e *Genre) Name() string { return e.Record().Name }

// SetName sets the name field.
func (e *Genre) SetName(v string) { e.Record().Name = v }

// Films returns a freshly allocated slice of entities over each
// Film in the multi-edge.
func (e *Genre) Films() []*Film {
	out := make([]*Film, len(e.Record().Films))
	for i, x := range e.Record().Films {
		out[i] = &Film{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// FilmsSeq returns an iterator over the Film entities, avoiding
// the allocation in Films().
func (e *Genre) FilmsSeq() iter.Seq[*Film] {
	return func(yield func(*Film) bool) {
		for _, x := range e.Record().Films {
			if !yield(&Film{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetFilms replaces the multi-edge with the given items.
func (e *Genre) SetFilms(items ...*Film) {
	e.Record().Films = make([]*schema.Film, len(items))
	for i, x := range items {
		e.Record().Films[i] = x.Record()
	}
}

// AppendFilms appends items to the multi-edge.
func (e *Genre) AppendFilms(items ...*Film) {
	for _, x := range items {
		e.Record().Films = append(e.Record().Films, x.Record())
	}
}

// RemoveFilms removes elements with any of the given UIDs from the multi-edge.
func (e *Genre) RemoveFilms(uids ...string) {
	e.Record().Films = slices.DeleteFunc(e.Record().Films, func(x *schema.Film) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// WithGenreName sets the name field on a *Genre.
func WithGenreName(v string) typed.Option[Genre] {
	return func(e *Genre) { e.SetName(v) }
}

// WithGenreFilms replaces the films multi-edge on a *Genre
// with the given items.
func WithGenreFilms(items ...*Film) typed.Option[Genre] {
	return func(e *Genre) { e.SetFilms(items...) }
}

// GenreClient provides CRUD/query operations over Genre entity values.
// It composes over a typed.Client bound to the record struct: reads wrap the
// record result, writes forward the entity's backing record.
type GenreClient struct {
	typed *typed.Client[schema.Genre]
}

// NewGenreClient binds a GenreClient to conn — the connection client or
// a transaction-scoped *dgdao.ClientTxn.
func NewGenreClient(conn dgdao.ClientCore) *GenreClient {
	return &GenreClient{typed: typed.NewClient[schema.Genre](conn)}
}

// InTxn returns a GenreClient whose reads and writes run within tx: reads
// join tx's read-set, writes stage on tx and land only on tx.Commit.
func (c *GenreClient) InTxn(tx *dgdao.Txn) *GenreClient {
	return &GenreClient{typed: c.typed.InTxn(tx)}
}

// Get loads the Genre with the given UID and returns it wrapped.
func (c *GenreClient) Get(ctx context.Context, uid string) (*Genre, error) {
	r, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return NewGenreWithRecord(r), nil
}

// Insert inserts the record struct backing e.
func (c *GenreClient) Insert(ctx context.Context, e *Genre) error {
	return c.typed.Insert(ctx, e.Record())
}

// Update modifies the record struct backing e (must have UID set).
func (c *GenreClient) Update(ctx context.Context, e *Genre) error {
	return c.typed.Update(ctx, e.Record())
}

// Upsert inserts or updates the record struct backing e, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *GenreClient) Upsert(ctx context.Context, e *Genre, predicates ...string) error {
	return c.typed.Upsert(ctx, e.Record(), predicates...)
}

// Delete removes the Genre with the given UID.
func (c *GenreClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns an entity-side query builder for Genre.
func (c *GenreClient) Query(ctx context.Context) *GenreQuery {
	return &GenreQuery{typed: c.typed.Query(ctx)}
}

// QueryRaw executes a raw DQL query with optional variables on the backing
// conn. On a transaction-scoped client the query reads within the
// transaction (read-your-writes).
func (c *GenreClient) QueryRaw(ctx context.Context, q string, vars map[string]string) ([]byte, error) {
	return c.typed.QueryRaw(ctx, q, vars)
}

// FulltextFields returns the DQL predicate names of Genre fields tagged
// with a "fulltext" index, in struct declaration order. Consumers iterate
// this list to build cross-field fulltext queries (e.g. typed.MultiQuery
// search) without hardcoding the field set; adding or removing a fulltext
// tag in the schema flows through on next `make generate`.
func (c *GenreClient) FulltextFields() []string {
	return []string{
		"name",
	}
}

// GenreQuery is the wrapper-side fluent query builder for Genre. Builder
// methods return *GenreQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type GenreQuery struct {
	typed *typed.Query[schema.Genre]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *GenreQuery) Filter(filter string, params ...any) *GenreQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *GenreQuery) OrderAsc(clause string) *GenreQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *GenreQuery) OrderDesc(clause string) *GenreQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *GenreQuery) Limit(n int) *GenreQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *GenreQuery) Offset(n int) *GenreQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *GenreQuery) After(uid string) *GenreQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *GenreQuery) Cascade(predicates ...string) *GenreQuery {
	q.typed.Cascade(predicates...)
	return q
}

// WhereFilms keeps only Genre records that have a ~genre
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *GenreQuery) WhereFilms(filter string, params ...any) *GenreQuery {
	q.typed.WhereEdge("~genre", filter, params...)
	return q
}

// WhereFilmsBy keeps only Genre records that have a ~genre
// edge whose target node matches the filter composed inside build — a typed
// FilmQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereFilms: no
// hand-written DQL or $N placeholders.
func (q *GenreQuery) WhereFilmsBy(build func(*FilmQuery)) *GenreQuery {
	sub := &FilmQuery{typed: typed.NewDetachedQuery[schema.Film]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("~genre", expr, params...)
	}
	return q
}

// ByName keeps only Genre records whose name matches one
// of filters. Terms within filters join with OR. Negated filters (Negated:true) become
// NOT eq(...). An empty filters slice is a no-op.
func (q *GenreQuery) ByName(filters ...filter.String) *GenreQuery {
	var b filter.Builder
	b.EqGroupString("name", filters)
	if expr, params := b.Build(); expr != "" {
		q.typed.Filter(expr, params...)
	}
	return q
}

// Or keeps only Genre records matching at least one of builders. Each builder
// receives a fresh GenreQuery whose By<Field>/Filter calls accumulate (ANDing
// within the builder); the builders' filters are ORed together and the whole
// group ANDs with the rest of the query. Builders that add no filter are
// skipped; an empty Or is a no-op.
func (q *GenreQuery) Or(builders ...func(*GenreQuery)) *GenreQuery {
	subs := make([]*typed.Query[schema.Genre], 0, len(builders))
	for _, build := range builders {
		sub := &GenreQuery{typed: typed.NewDetachedQuery[schema.Genre]()}
		build(sub)
		subs = append(subs, sub.typed)
	}
	q.typed.OrGroup(subs...)
	return q
}

// Nodes executes the query and returns the Genre entities.
func (q *GenreQuery) Nodes() ([]*Genre, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Genre, len(recs))
	for i := range recs {
		out[i] = NewGenreWithRecord(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// Genre entity, or nil if no rows matched.
func (q *GenreQuery) First() (*Genre, error) {
	r, err := q.typed.First()
	if err != nil || r == nil {
		return nil, err
	}
	return NewGenreWithRecord(r), nil
}

// IterNodes streams the query's results as Genre entities, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *GenreQuery) IterNodes() iter.Seq2[*Genre, error] {
	return func(yield func(*Genre, error) bool) {
		for r, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(NewGenreWithRecord(r), nil) {
				return
			}
		}
	}
}
