// Code generated by dgdao-gen. DO NOT EDIT.

package movies

import (
	"context"
	"iter"
	"slices"

	"github.com/dgraph-io/dgdao"
	"github.com/dgraph-io/dgdao/typed"
	"github.com/dgraph-io/dgdao/typed/filter"

	"github.com/dgraph-io/dgdao-gen/cmd/dgdao-gen/internal/parser/testdata/movies/schema"
)

// Location wraps a schema.Location record and exposes its data through
// methods. It embeds dgdao.Entity, which supplies Record, JSON marshaling,
// and validation; the backing record struct is reachable only via Record().
type Location struct {
	dgdao.Entity[schema.Location]
}

// NewLocation constructs a Location with a fresh, empty record struct, then
// applies the given options.
func NewLocation(opts ...typed.Option[Location]) *Location {
	e := &Location{Entity: dgdao.AsEntity(&schema.Location{})}
	typed.Apply(e, opts...)
	return e
}

// NewLocationWithRecord constructs a Location backed by the given record
// struct, then applies the given options. The entity adopts r directly — no
// defensive copy, so setters mutate the caller's struct.
func NewLocationWithRecord(r *schema.Location, opts ...typed.Option[Location]) *Location {
	e := &Location{Entity: dgdao.AsEntity(r)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Location) UID() string { return e.Record().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Location) SetUID(v string) { e.Record().UID = v }

// DType returns the entity's dgraph type list.
func (e *Location) DType() []string { return e.Record().DType }

// SetDType sets the entity's dgraph type list.
func (e *Location) SetDType(v []string) { e.Record().DType = v }

// Name returns the name field.
func (e *Location) Name() string { return e.Record().Name }

// SetName sets the name field.
func (e *Location) SetName(v string) { e.Record().Name = v }

// Email returns the email field.
func (e *Location) Email() string { return e.Record().Email }

// SetEmail sets the email field.
func (e *Location) SetEmail(v string) { e.Record().Email = v }

// Loc returns the scalar slice.
func (e *Location) Loc() []float64 { return e.Record().Loc }

// SetLoc sets the scalar slice.
func (e *Location) SetLoc(v []float64) { e.Record().Loc = v }

// AppendLoc appends values to the scalar slice.
func (e *Location) AppendLoc(v ...float64) {
	e.Record().Loc = append(e.Record().Loc, v...)
}

// RemoveLocFunc removes all elements for which fn returns true.
func (e *Location) RemoveLocFunc(fn func(float64) bool) {
	e.Record().Loc = slices.DeleteFunc(e.Record().Loc, fn)
}

// WithLocationName sets the name field on a *Location.
func WithLocationName(v string) typed.Option[Location] {
	return func(e *Location) { e.SetName(v) }
}

// WithLocationEmail sets the email field on a *Location.
func WithLocationEmail(v string) typed.Option[Location] {
	return func(e *Location) { e.SetEmail(v) }
}

// LocationClient provides CRUD/query operations over Location entity values.
// It composes over a typed.Client bound to the record struct: reads wrap the
// record result, writes forward the entity's backing record.
type LocationClient struct {
	typed *typed.Client[schema.Location]
}

// NewLocationClient binds a LocationClient to conn — the connection client or
// a transaction-scoped *dgdao.ClientTxn.
func NewLocationClient(conn dgdao.ClientCore) *LocationClient {
	return &LocationClient{typed: typed.NewClient[schema.Location](conn)}
}

// InTxn returns a LocationClient whose reads and writes run within tx: reads
// join tx's read-set, writes stage on tx and land only on tx.Commit.
func (c *LocationClient) InTxn(tx *dgdao.Txn) *LocationClient {
	return &LocationClient{typed: c.typed.InTxn(tx)}
}

// Get loads the Location with the given UID and returns it wrapped.
func (c *LocationClient) Get(ctx context.Context, uid string) (*Location, error) {
	r, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return NewLocationWithRecord(r), nil
}

// Insert inserts the record struct backing e.
func (c *LocationClient) Insert(ctx context.Context, e *Location) error {
	return c.typed.Insert(ctx, e.Record())
}

// Update modifies the record struct backing e (must have UID set).
func (c *LocationClient) Update(ctx context.Context, e *Location) error {
	return c.typed.Update(ctx, e.Record())
}

// Upsert inserts or updates the record struct backing e, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *LocationClient) Upsert(ctx context.Context, e *Location, predicates ...string) error {
	return c.typed.Upsert(ctx, e.Record(), predicates...)
}

// GetAndDelete atomically reads the Location whose email equals
// key and deletes it, returning (nil, false, nil) when none matched.
// Concurrent callers racing on one key elect a single winner: exactly one
// observes loaded=true. Use it to consume single-use records, where the read
// must also invalidate. (cf. sync.Map.LoadAndDelete)
func (c *LocationClient) GetAndDelete(ctx context.Context, key string) (*Location, bool, error) {
	r, loaded, err := c.typed.GetAndDelete(ctx, key, "email")
	if err != nil || !loaded {
		return nil, loaded, err
	}
	return NewLocationWithRecord(r), true, nil
}

// GetOrInsert atomically gets the Location with the same email,
// or inserts the record backing e when none exists, returning loaded=true
// when one already existed. Concurrent callers racing on one key elect a
// single winner: exactly one inserts. Use it for idempotent creation —
// "ensure this record exists". (cf. sync.Map.LoadOrStore)
func (c *LocationClient) GetOrInsert(ctx context.Context, e *Location) (*Location, bool, error) {
	r, loaded, err := c.typed.GetOrInsert(ctx, e.Record(), "email")
	if err != nil {
		return nil, false, err
	}
	return NewLocationWithRecord(r), loaded, nil
}

// Delete removes the Location with the given UID.
func (c *LocationClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns an entity-side query builder for Location.
func (c *LocationClient) Query(ctx context.Context) *LocationQuery {
	return &LocationQuery{typed: c.typed.Query(ctx)}
}

// QueryRaw executes a raw DQL query with optional variables on the backing
// conn. On a transaction-scoped client the query reads within the
// transaction (read-your-writes).
func (c *LocationClient) QueryRaw(ctx context.Context, q string, vars map[string]string) ([]byte, error) {
	return c.typed.QueryRaw(ctx, q, vars)
}

// FulltextFields returns the DQL predicate names of Location fields tagged
// with a "fulltext" index, in struct declaration order. Consumers iterate
// this list to build cross-field fulltext queries (e.g. typed.MultiQuery
// search) without hardcoding the field set; adding or removing a fulltext
// tag in the schema flows through on next `make generate`.
func (c *LocationClient) FulltextFields() []string {
	return []string{
		"name",
	}
}

// LocationQuery is the wrapper-side fluent query builder for Location. Builder
// methods return *LocationQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type LocationQuery struct {
	typed *typed.Query[schema.Location]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *LocationQuery) Filter(filter string, params ...any) *LocationQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *LocationQuery) OrderAsc(clause string) *LocationQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *LocationQuery) OrderDesc(clause string) *LocationQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *LocationQuery) Limit(n int) *LocationQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *LocationQuery) Offset(n int) *LocationQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *LocationQuery) After(uid string) *LocationQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *LocationQuery) Cascade(predicates ...string) *LocationQuery {
	q.typed.Cascade(predicates...)
	return q
}

// ByName keeps only Location records whose name matches one
// of filters. Terms within filters join with OR. Negated filters (Negated:true) become
// NOT eq(...). An empty filters slice is a no-op.
func (q *LocationQuery) ByName(filters ...filter.String) *LocationQuery {
	var b filter.Builder
	b.EqGroupString("name", filters)
	if expr, params := b.Build(); expr != "" {
		q.typed.Filter(expr, params...)
	}
	return q
}

// ByEmail keeps only Location records whose email matches one
// of filters. Terms within filters join with OR. Negated filters (Negated:true) become
// NOT eq(...). An empty filters slice is a no-op.
func (q *LocationQuery) ByEmail(filters ...filter.String) *LocationQuery {
	var b filter.Builder
	b.EqGroupString("email", filters)
	if expr, params := b.Build(); expr != "" {
		q.typed.Filter(expr, params...)
	}
	return q
}

// Or keeps only Location records matching at least one of builders. Each builder
// receives a fresh LocationQuery whose By<Field>/Filter calls accumulate (ANDing
// within the builder); the builders' filters are ORed together and the whole
// group ANDs with the rest of the query. Builders that add no filter are
// skipped; an empty Or is a no-op.
func (q *LocationQuery) Or(builders ...func(*LocationQuery)) *LocationQuery {
	subs := make([]*typed.Query[schema.Location], 0, len(builders))
	for _, build := range builders {
		sub := &LocationQuery{typed: typed.NewDetachedQuery[schema.Location]()}
		build(sub)
		subs = append(subs, sub.typed)
	}
	q.typed.OrGroup(subs...)
	return q
}

// Nodes executes the query and returns the Location entities.
func (q *LocationQuery) Nodes() ([]*Location, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Location, len(recs))
	for i := range recs {
		out[i] = NewLocationWithRecord(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// Location entity, or nil if no rows matched.
func (q *LocationQuery) First() (*Location, error) {
	r, err := q.typed.First()
	if err != nil || r == nil {
		return nil, err
	}
	return NewLocationWithRecord(r), nil
}

// IterNodes streams the query's results as Location entities, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *LocationQuery) IterNodes() iter.Seq2[*Location, error] {
	return func(yield func(*Location, error) bool) {
		for r, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(NewLocationWithRecord(r), nil) {
				return
			}
		}
	}
}
