// Code generated by dgdao-gen. DO NOT EDIT.

package movies

import (
	"context"
	"iter"

	"github.com/dgraph-io/dgdao"
	"github.com/dgraph-io/dgdao/typed"

	"github.com/dgraph-io/dgdao-gen/cmd/dgdao-gen/internal/parser/testdata/movies/schema"
)

// Performance wraps a schema.Performance record and exposes its data through
// methods. It embeds dgdao.Entity, which supplies Record, JSON marshaling,
// and validation; the backing record struct is reachable only via Record().
type Performance struct {
	dgdao.Entity[schema.Performance]
}

// NewPerformance constructs a Performance with a fresh, empty record struct, then
// applies the given options.
func NewPerformance(opts ...typed.Option[Performance]) *Performance {
	e := &Performance{Entity: dgdao.AsEntity(&schema.Performance{})}
	typed.Apply(e, opts...)
	return e
}

// NewPerformanceWithRecord constructs a Performance backed by the given record
// struct, then applies the given options. The entity adopts r directly — no
// defensive copy, so setters mutate the caller's struct.
func NewPerformanceWithRecord(r *schema.Performance, opts ...typed.Option[Performance]) *Performance {
	e := &Performance{Entity: dgdao.AsEntity(r)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Performance) UID() string { return e.Record().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Performance) SetUID(v string) { e.Record().UID = v }

// DType returns the entity's dgraph type list.
func (e *Performance) DType() []string { return e.Record().DType }

// SetDType sets the entity's dgraph type list.
func (e *Performance) SetDType(v []string) { e.Record().DType = v }

// CharacterNote returns the characterNote field.
func (e *Performance) CharacterNote() string { return e.Record().CharacterNote }

// SetCharacterNote sets the characterNote field.
func (e *Performance) SetCharacterNote(v string) { e.Record().CharacterNote = v }

// WithPerformanceCharacterNote sets the characterNote field on a *Performance.
func WithPerformanceCharacterNote(v string) typed.Option[Performance] {
	return func(e *Performance) { e.SetCharacterNote(v) }
}

// PerformanceClient provides CRUD/query operations over Performance entity values.
// It composes over a typed.Client bound to the record struct: reads wrap the
// record result, writes forward the entity's backing record.
type PerformanceClient struct {
	typed *typed.Client[schema.Performance]
}

// NewPerformanceClient binds a PerformanceClient to conn — the connection client or
// a transaction-scoped *dgdao.ClientTxn.
func NewPerformanceClient(conn dgdao.ClientCore) *PerformanceClient {
	return &PerformanceClient{typed: typed.NewClient[schema.Performance](conn)}
}

// InTxn returns a PerformanceClient whose reads and writes run within tx: reads
// join tx's read-set, writes stage on tx and land only on tx.Commit.
func (c *PerformanceClient) InTxn(tx *dgdao.Txn) *PerformanceClient {
	return &PerformanceClient{typed: c.typed.InTxn(tx)}
}

// Get loads the Performance with the given UID and returns it wrapped.
func (c *PerformanceClient) Get(ctx context.Context, uid string) (*Performance, error) {
	r, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return NewPerformanceWithRecord(r), nil
}

// Insert inserts the record struct backing e.
func (c *PerformanceClient) Insert(ctx context.Context, e *Performance) error {
	return c.typed.Insert(ctx, e.Record())
}

// Update modifies the record struct backing e (must have UID set).
func (c *PerformanceClient) Update(ctx context.Context, e *Performance) error {
	return c.typed.Update(ctx, e.Record())
}

// Upsert inserts or updates the record struct backing e, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *PerformanceClient) Upsert(ctx context.Context, e *Performance, predicates ...string) error {
	return c.typed.Upsert(ctx, e.Record(), predicates...)
}

// Delete removes the Performance with the given UID.
func (c *PerformanceClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns an entity-side query builder for Performance.
func (c *PerformanceClient) Query(ctx context.Context) *PerformanceQuery {
	return &PerformanceQuery{typed: c.typed.Query(ctx)}
}

// QueryRaw executes a raw DQL query with optional variables on the backing
// conn. On a transaction-scoped client the query reads within the
// transaction (read-your-writes).
func (c *PerformanceClient) QueryRaw(ctx context.Context, q string, vars map[string]string) ([]byte, error) {
	return c.typed.QueryRaw(ctx, q, vars)
}

// FulltextFields returns the DQL predicate names of Performance fields tagged
// with a "fulltext" index, in struct declaration order. Consumers iterate
// this list to build cross-field fulltext queries (e.g. typed.MultiQuery
// search) without hardcoding the field set; adding or removing a fulltext
// tag in the schema flows through on next `make generate`.
func (c *PerformanceClient) FulltextFields() []string {
	return []string{}
}

// PerformanceQuery is the wrapper-side fluent query builder for Performance. Builder
// methods return *PerformanceQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type PerformanceQuery struct {
	typed *typed.Query[schema.Performance]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *PerformanceQuery) Filter(filter string, params ...any) *PerformanceQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *PerformanceQuery) OrderAsc(clause string) *PerformanceQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *PerformanceQuery) OrderDesc(clause string) *PerformanceQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *PerformanceQuery) Limit(n int) *PerformanceQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *PerformanceQuery) Offset(n int) *PerformanceQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *PerformanceQuery) After(uid string) *PerformanceQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *PerformanceQuery) Cascade(predicates ...string) *PerformanceQuery {
	q.typed.Cascade(predicates...)
	return q
}

// Or keeps only Performance records matching at least one of builders. Each builder
// receives a fresh PerformanceQuery whose By<Field>/Filter calls accumulate (ANDing
// within the builder); the builders' filters are ORed together and the whole
// group ANDs with the rest of the query. Builders that add no filter are
// skipped; an empty Or is a no-op.
func (q *PerformanceQuery) Or(builders ...func(*PerformanceQuery)) *PerformanceQuery {
	subs := make([]*typed.Query[schema.Performance], 0, len(builders))
	for _, build := range builders {
		sub := &PerformanceQuery{typed: typed.NewDetachedQuery[schema.Performance]()}
		build(sub)
		subs = append(subs, sub.typed)
	}
	q.typed.OrGroup(subs...)
	return q
}

// Nodes executes the query and returns the Performance entities.
func (q *PerformanceQuery) Nodes() ([]*Performance, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Performance, len(recs))
	for i := range recs {
		out[i] = NewPerformanceWithRecord(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// Performance entity, or nil if no rows matched.
func (q *PerformanceQuery) First() (*Performance, error) {
	r, err := q.typed.First()
	if err != nil || r == nil {
		return nil, err
	}
	return NewPerformanceWithRecord(r), nil
}

// IterNodes streams the query's results as Performance entities, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *PerformanceQuery) IterNodes() iter.Seq2[*Performance, error] {
	return func(yield func(*Performance, error) bool) {
		for r, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(NewPerformanceWithRecord(r), nil) {
				return
			}
		}
	}
}
