// Code generated by dgdao-gen. DO NOT EDIT.

package movies

import (
	"context"
	"iter"
	"slices"
	"time"

	"github.com/dgraph-io/dgdao"
	"github.com/dgraph-io/dgdao/typed"
	"github.com/dgraph-io/dgdao/typed/filter"

	"github.com/dgraph-io/dgdao-gen/cmd/dgdao-gen/internal/parser/testdata/movies/schema"
	dg "github.com/dolan-in/dgman/v2"
)

// Studio wraps a schema.Studio record and exposes its data through
// methods. It embeds dgdao.Entity, which supplies Record, JSON marshaling,
// and validation; the backing record struct is reachable only via Record().
type Studio struct {
	dgdao.Entity[schema.Studio]
}

// NewStudio constructs a Studio with a fresh, empty record struct, then
// applies the given options.
func NewStudio(opts ...typed.Option[Studio]) *Studio {
	e := &Studio{Entity: dgdao.AsEntity(&schema.Studio{})}
	typed.Apply(e, opts...)
	return e
}

// NewStudioWithRecord constructs a Studio backed by the given record
// struct, then applies the given options. The entity adopts r directly — no
// defensive copy, so setters mutate the caller's struct.
func NewStudioWithRecord(r *schema.Studio, opts ...typed.Option[Studio]) *Studio {
	e := &Studio{Entity: dgdao.AsEntity(r)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Studio) UID() string { return e.Record().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Studio) SetUID(v string) { e.Record().UID = v }

// DType returns the entity's dgraph type list.
func (e *Studio) DType() []string { return e.Record().DType }

// SetDType sets the entity's dgraph type list.
func (e *Studio) SetDType(v []string) { e.Record().DType = v }

// Name returns the name field.
func (e *Studio) Name() string { return e.Record().Name }

// SetName sets the name field.
func (e *Studio) SetName(v string) { e.Record().Name = v }

// YearFounded returns the yearFounded field.
func (e *Studio) YearFounded() int { return e.Record().YearFounded }

// SetYearFounded sets the yearFounded field.
func (e *Studio) SetYearFounded(v int) { e.Record().YearFounded = v }

// Revenue returns the revenue field.
func (e *Studio) Revenue() float64 { return e.Record().Revenue }

// SetRevenue sets the revenue field.
func (e *Studio) SetRevenue(v float64) { e.Record().Revenue = v }

// Active returns the active field.
func (e *Studio) Active() bool { return e.Record().Active }

// SetActive sets the active field.
func (e *Studio) SetActive(v bool) { e.Record().Active = v }

// CreatedAt returns the createdAt field.
func (e *Studio) CreatedAt() time.Time { return e.Record().CreatedAt }

// SetCreatedAt sets the createdAt field.
func (e *Studio) SetCreatedAt(v time.Time) { e.Record().CreatedAt = v }

// Embedding returns the embedding field.
func (e *Studio) Embedding() *dg.VectorFloat32 { return e.Record().Embedding }

// SetEmbedding sets the embedding field.
func (e *Studio) SetEmbedding(v *dg.VectorFloat32) { e.Record().Embedding = v }

// Founder returns the Director entity, or nil if not set.
// Shared state: mutations through the returned entity write through to e.
func (e *Studio) Founder() *Director {
	if e.Record().Founder == nil {
		return nil
	}
	return &Director{Entity: dgdao.AsEntity(e.Record().Founder)}
}

// SetFounder sets or clears the Director edge.
func (e *Studio) SetFounder(v *Director) {
	if v == nil {
		e.Record().Founder = nil
		return
	}
	e.Record().Founder = v.Record()
}

// Headquarters returns an entity over the value-typed record field. The entity
// shares state with e — mutations are visible to e immediately.
func (e *Studio) Headquarters() *Country {
	return &Country{Entity: dgdao.AsEntity(&e.Record().Headquarters)}
}

// SetHeadquarters copies the value from v into the record field. Note: this is
// a value copy, so v and e.Headquarters() will not share state after this call.
func (e *Studio) SetHeadquarters(v *Country) {
	if v != nil {
		e.Record().Headquarters = *v.Record()
	}
}

// CurrentHead returns the first element of the singular-via-list edge as an entity,
// or nil if the list is empty.
func (e *Studio) CurrentHead() *Director {
	if len(e.Record().CurrentHead) == 0 || e.Record().CurrentHead[0] == nil {
		return nil
	}
	return &Director{Entity: dgdao.AsEntity(e.Record().CurrentHead[0])}
}

// SetCurrentHead replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetCurrentHead(v *Director) {
	if v == nil {
		e.Record().CurrentHead = nil
		return
	}
	e.Record().CurrentHead = []*schema.Director{v.Record()}
}

// Ceo returns the first element of the singular-via-list edge as an entity,
// or nil if the list is empty.
func (e *Studio) Ceo() *Director {
	if len(e.Record().Ceo) == 0 || e.Record().Ceo[0] == nil {
		return nil
	}
	return &Director{Entity: dgdao.AsEntity(e.Record().Ceo[0])}
}

// SetCeo replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetCeo(v *Director) {
	if v == nil {
		e.Record().Ceo = nil
		return
	}
	e.Record().Ceo = []*schema.Director{v.Record()}
}

// HomeBase returns the first element of the singular-via-list edge as an entity,
// or nil if the list is empty.
func (e *Studio) HomeBase() *Country {
	if len(e.Record().HomeBase) == 0 || e.Record().HomeBase[0] == nil {
		return nil
	}
	return &Country{Entity: dgdao.AsEntity(e.Record().HomeBase[0])}
}

// SetHomeBase replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetHomeBase(v *Country) {
	if v == nil {
		e.Record().HomeBase = nil
		return
	}
	e.Record().HomeBase = []*schema.Country{v.Record()}
}

// ParentCompany returns the first element of the singular-via-list edge as an entity,
// or nil if the list is empty.
func (e *Studio) ParentCompany() *Country {
	if len(e.Record().ParentCompany) == 0 || e.Record().ParentCompany[0] == nil {
		return nil
	}
	return &Country{Entity: dgdao.AsEntity(e.Record().ParentCompany[0])}
}

// SetParentCompany replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetParentCompany(v *Country) {
	if v == nil {
		e.Record().ParentCompany = nil
		return
	}
	e.Record().ParentCompany = []*schema.Country{v.Record()}
}

// Films returns a freshly allocated slice of entities over each
// Film in the multi-edge.
func (e *Studio) Films() []*Film {
	out := make([]*Film, len(e.Record().Films))
	for i, x := range e.Record().Films {
		out[i] = &Film{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// FilmsSeq returns an iterator over the Film entities, avoiding
// the allocation in Films().
func (e *Studio) FilmsSeq() iter.Seq[*Film] {
	return func(yield func(*Film) bool) {
		for _, x := range e.Record().Films {
			if !yield(&Film{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetFilms replaces the multi-edge with the given items.
func (e *Studio) SetFilms(items ...*Film) {
	e.Record().Films = make([]*schema.Film, len(items))
	for i, x := range items {
		e.Record().Films[i] = x.Record()
	}
}

// AppendFilms appends items to the multi-edge.
func (e *Studio) AppendFilms(items ...*Film) {
	for _, x := range items {
		e.Record().Films = append(e.Record().Films, x.Record())
	}
}

// RemoveFilms removes elements with any of the given UIDs from the multi-edge.
func (e *Studio) RemoveFilms(uids ...string) {
	e.Record().Films = slices.DeleteFunc(e.Record().Films, func(x *schema.Film) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Advisors returns a freshly allocated slice of entities over each
// Director in the multi-edge.
func (e *Studio) Advisors() []*Director {
	out := make([]*Director, len(e.Record().Advisors))
	for i, x := range e.Record().Advisors {
		out[i] = &Director{Entity: dgdao.AsEntity(x)}
	}
	return out
}

// AdvisorsSeq returns an iterator over the Director entities, avoiding
// the allocation in Advisors().
func (e *Studio) AdvisorsSeq() iter.Seq[*Director] {
	return func(yield func(*Director) bool) {
		for _, x := range e.Record().Advisors {
			if !yield(&Director{Entity: dgdao.AsEntity(x)}) {
				return
			}
		}
	}
}

// SetAdvisors replaces the multi-edge with the given items.
func (e *Studio) SetAdvisors(items ...*Director) {
	e.Record().Advisors = make([]*schema.Director, len(items))
	for i, x := range items {
		e.Record().Advisors[i] = x.Record()
	}
}

// AppendAdvisors appends items to the multi-edge.
func (e *Studio) AppendAdvisors(items ...*Director) {
	for _, x := range items {
		e.Record().Advisors = append(e.Record().Advisors, x.Record())
	}
}

// RemoveAdvisors removes elements with any of the given UIDs from the multi-edge.
func (e *Studio) RemoveAdvisors(uids ...string) {
	e.Record().Advisors = slices.DeleteFunc(e.Record().Advisors, func(x *schema.Director) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Tags returns the scalar slice.
func (e *Studio) Tags() []string { return e.Record().Tags }

// SetTags sets the scalar slice.
func (e *Studio) SetTags(v []string) { e.Record().Tags = v }

// AppendTags appends values to the scalar slice.
func (e *Studio) AppendTags(v ...string) {
	e.Record().Tags = append(e.Record().Tags, v...)
}

// RemoveTagsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveTagsFunc(fn func(string) bool) {
	e.Record().Tags = slices.DeleteFunc(e.Record().Tags, fn)
}

// Scores returns the scalar slice.
func (e *Studio) Scores() []int { return e.Record().Scores }

// SetScores sets the scalar slice.
func (e *Studio) SetScores(v []int) { e.Record().Scores = v }

// AppendScores appends values to the scalar slice.
func (e *Studio) AppendScores(v ...int) {
	e.Record().Scores = append(e.Record().Scores, v...)
}

// RemoveScoresFunc removes all elements for which fn returns true.
func (e *Studio) RemoveScoresFunc(fn func(int) bool) {
	e.Record().Scores = slices.DeleteFunc(e.Record().Scores, fn)
}

// Weights returns the scalar slice.
func (e *Studio) Weights() []float64 { return e.Record().Weights }

// SetWeights sets the scalar slice.
func (e *Studio) SetWeights(v []float64) { e.Record().Weights = v }

// AppendWeights appends values to the scalar slice.
func (e *Studio) AppendWeights(v ...float64) {
	e.Record().Weights = append(e.Record().Weights, v...)
}

// RemoveWeightsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveWeightsFunc(fn func(float64) bool) {
	e.Record().Weights = slices.DeleteFunc(e.Record().Weights, fn)
}

// Flags returns the scalar slice.
func (e *Studio) Flags() []bool { return e.Record().Flags }

// SetFlags sets the scalar slice.
func (e *Studio) SetFlags(v []bool) { e.Record().Flags = v }

// AppendFlags appends values to the scalar slice.
func (e *Studio) AppendFlags(v ...bool) {
	e.Record().Flags = append(e.Record().Flags, v...)
}

// RemoveFlagsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveFlagsFunc(fn func(bool) bool) {
	e.Record().Flags = slices.DeleteFunc(e.Record().Flags, fn)
}

// Milestones returns the scalar slice.
func (e *Studio) Milestones() []time.Time { return e.Record().Milestones }

// SetMilestones sets the scalar slice.
func (e *Studio) SetMilestones(v []time.Time) { e.Record().Milestones = v }

// AppendMilestones appends values to the scalar slice.
func (e *Studio) AppendMilestones(v ...time.Time) {
	e.Record().Milestones = append(e.Record().Milestones, v...)
}

// RemoveMilestonesFunc removes all elements for which fn returns true.
func (e *Studio) RemoveMilestonesFunc(fn func(time.Time) bool) {
	e.Record().Milestones = slices.DeleteFunc(e.Record().Milestones, fn)
}

// WithStudioName sets the name field on a *Studio.
func WithStudioName(v string) typed.Option[Studio] {
	return func(e *Studio) { e.SetName(v) }
}

// WithStudioYearFounded sets the yearFounded field on a *Studio.
func WithStudioYearFounded(v int) typed.Option[Studio] {
	return func(e *Studio) { e.SetYearFounded(v) }
}

// WithStudioRevenue sets the revenue field on a *Studio.
func WithStudioRevenue(v float64) typed.Option[Studio] {
	return func(e *Studio) { e.SetRevenue(v) }
}

// WithStudioActive sets the active field on a *Studio.
func WithStudioActive(v bool) typed.Option[Studio] {
	return func(e *Studio) { e.SetActive(v) }
}

// WithStudioCreatedAt sets the createdAt field on a *Studio.
func WithStudioCreatedAt(v time.Time) typed.Option[Studio] {
	return func(e *Studio) { e.SetCreatedAt(v) }
}

// WithStudioEmbedding sets the embedding field on a *Studio.
func WithStudioEmbedding(v *dg.VectorFloat32) typed.Option[Studio] {
	return func(e *Studio) { e.SetEmbedding(v) }
}

// WithStudioFounder sets the founder edge on a *Studio.
func WithStudioFounder(v *Director) typed.Option[Studio] {
	return func(e *Studio) { e.SetFounder(v) }
}

// WithStudioHeadquarters sets the headquarters edge on a *Studio (value copy).
func WithStudioHeadquarters(v *Country) typed.Option[Studio] {
	return func(e *Studio) { e.SetHeadquarters(v) }
}

// WithStudioCurrentHead sets the currentHead singular-via-list edge on a *Studio.
func WithStudioCurrentHead(v *Director) typed.Option[Studio] {
	return func(e *Studio) { e.SetCurrentHead(v) }
}

// WithStudioCeo sets the ceo singular-via-list edge on a *Studio.
func WithStudioCeo(v *Director) typed.Option[Studio] {
	return func(e *Studio) { e.SetCeo(v) }
}

// WithStudioHomeBase sets the homeBase singular-via-list edge on a *Studio.
func WithStudioHomeBase(v *Country) typed.Option[Studio] {
	return func(e *Studio) { e.SetHomeBase(v) }
}

// WithStudioParentCompany sets the parentCompany singular-via-list edge on a *Studio.
func WithStudioParentCompany(v *Country) typed.Option[Studio] {
	return func(e *Studio) { e.SetParentCompany(v) }
}

// WithStudioFilms replaces the films multi-edge on a *Studio
// with the given items.
func WithStudioFilms(items ...*Film) typed.Option[Studio] {
	return func(e *Studio) { e.SetFilms(items...) }
}

// WithStudioAdvisors replaces the advisors multi-edge on a *Studio
// with the given items.
func WithStudioAdvisors(items ...*Director) typed.Option[Studio] {
	return func(e *Studio) { e.SetAdvisors(items...) }
}

// StudioClient provides CRUD/query operations over Studio entity values.
// It composes over a typed.Client bound to the record struct: reads wrap the
// record result, writes forward the entity's backing record.
type StudioClient struct {
	typed *typed.Client[schema.Studio]
}

// NewStudioClient binds a StudioClient to conn — the connection client or
// a transaction-scoped *dgdao.ClientTxn.
func NewStudioClient(conn dgdao.ClientCore) *StudioClient {
	return &StudioClient{typed: typed.NewClient[schema.Studio](conn)}
}

// InTxn returns a StudioClient whose reads and writes run within tx: reads
// join tx's read-set, writes stage on tx and land only on tx.Commit.
func (c *StudioClient) InTxn(tx *dgdao.Txn) *StudioClient {
	return &StudioClient{typed: c.typed.InTxn(tx)}
}

// Get loads the Studio with the given UID and returns it wrapped.
func (c *StudioClient) Get(ctx context.Context, uid string) (*Studio, error) {
	r, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return NewStudioWithRecord(r), nil
}

// Insert inserts the record struct backing e.
func (c *StudioClient) Insert(ctx context.Context, e *Studio) error {
	return c.typed.Insert(ctx, e.Record())
}

// Update modifies the record struct backing e (must have UID set).
func (c *StudioClient) Update(ctx context.Context, e *Studio) error {
	return c.typed.Update(ctx, e.Record())
}

// Upsert inserts or updates the record struct backing e, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *StudioClient) Upsert(ctx context.Context, e *Studio, predicates ...string) error {
	return c.typed.Upsert(ctx, e.Record(), predicates...)
}

// Delete removes the Studio with the given UID.
func (c *StudioClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns an entity-side query builder for Studio.
func (c *StudioClient) Query(ctx context.Context) *StudioQuery {
	return &StudioQuery{typed: c.typed.Query(ctx)}
}

// QueryRaw executes a raw DQL query with optional variables on the backing
// conn. On a transaction-scoped client the query reads within the
// transaction (read-your-writes).
func (c *StudioClient) QueryRaw(ctx context.Context, q string, vars map[string]string) ([]byte, error) {
	return c.typed.QueryRaw(ctx, q, vars)
}

// FulltextFields returns the DQL predicate names of Studio fields tagged
// with a "fulltext" index, in struct declaration order. Consumers iterate
// this list to build cross-field fulltext queries (e.g. typed.MultiQuery
// search) without hardcoding the field set; adding or removing a fulltext
// tag in the schema flows through on next `make generate`.
func (c *StudioClient) FulltextFields() []string {
	return []string{}
}

// StudioQuery is the wrapper-side fluent query builder for Studio. Builder
// methods return *StudioQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type StudioQuery struct {
	typed *typed.Query[schema.Studio]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *StudioQuery) Filter(filter string, params ...any) *StudioQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *StudioQuery) OrderAsc(clause string) *StudioQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *StudioQuery) OrderDesc(clause string) *StudioQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *StudioQuery) Limit(n int) *StudioQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *StudioQuery) Offset(n int) *StudioQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *StudioQuery) After(uid string) *StudioQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *StudioQuery) Cascade(predicates ...string) *StudioQuery {
	q.typed.Cascade(predicates...)
	return q
}

// WhereFounder keeps only Studio records that have a founder
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *StudioQuery) WhereFounder(filter string, params ...any) *StudioQuery {
	q.typed.WhereEdge("founder", filter, params...)
	return q
}

// WhereFounderBy keeps only Studio records that have a founder
// edge whose target node matches the filter composed inside build — a typed
// DirectorQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereFounder: no
// hand-written DQL or $N placeholders.
func (q *StudioQuery) WhereFounderBy(build func(*DirectorQuery)) *StudioQuery {
	sub := &DirectorQuery{typed: typed.NewDetachedQuery[schema.Director]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("founder", expr, params...)
	}
	return q
}

// WhereHeadquarters keeps only Studio records that have a headquarters
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *StudioQuery) WhereHeadquarters(filter string, params ...any) *StudioQuery {
	q.typed.WhereEdge("headquarters", filter, params...)
	return q
}

// WhereHeadquartersBy keeps only Studio records that have a headquarters
// edge whose target node matches the filter composed inside build — a typed
// CountryQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereHeadquarters: no
// hand-written DQL or $N placeholders.
func (q *StudioQuery) WhereHeadquartersBy(build func(*CountryQuery)) *StudioQuery {
	sub := &CountryQuery{typed: typed.NewDetachedQuery[schema.Country]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("headquarters", expr, params...)
	}
	return q
}

// WhereCurrentHead keeps only Studio records that have a currentHead
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *StudioQuery) WhereCurrentHead(filter string, params ...any) *StudioQuery {
	q.typed.WhereEdge("currentHead", filter, params...)
	return q
}

// WhereCurrentHeadBy keeps only Studio records that have a currentHead
// edge whose target node matches the filter composed inside build — a typed
// DirectorQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereCurrentHead: no
// hand-written DQL or $N placeholders.
func (q *StudioQuery) WhereCurrentHeadBy(build func(*DirectorQuery)) *StudioQuery {
	sub := &DirectorQuery{typed: typed.NewDetachedQuery[schema.Director]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("currentHead", expr, params...)
	}
	return q
}

// WhereCeo keeps only Studio records that have a ceo
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *StudioQuery) WhereCeo(filter string, params ...any) *StudioQuery {
	q.typed.WhereEdge("ceo", filter, params...)
	return q
}

// WhereCeoBy keeps only Studio records that have a ceo
// edge whose target node matches the filter composed inside build — a typed
// DirectorQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereCeo: no
// hand-written DQL or $N placeholders.
func (q *StudioQuery) WhereCeoBy(build func(*DirectorQuery)) *StudioQuery {
	sub := &DirectorQuery{typed: typed.NewDetachedQuery[schema.Director]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("ceo", expr, params...)
	}
	return q
}

// WhereHomeBase keeps only Studio records that have a homeBase
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *StudioQuery) WhereHomeBase(filter string, params ...any) *StudioQuery {
	q.typed.WhereEdge("homeBase", filter, params...)
	return q
}

// WhereHomeBaseBy keeps only Studio records that have a homeBase
// edge whose target node matches the filter composed inside build — a typed
// CountryQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereHomeBase: no
// hand-written DQL or $N placeholders.
func (q *StudioQuery) WhereHomeBaseBy(build func(*CountryQuery)) *StudioQuery {
	sub := &CountryQuery{typed: typed.NewDetachedQuery[schema.Country]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("homeBase", expr, params...)
	}
	return q
}

// WhereParentCompany keeps only Studio records that have a parentCompany
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *StudioQuery) WhereParentCompany(filter string, params ...any) *StudioQuery {
	q.typed.WhereEdge("parentCompany", filter, params...)
	return q
}

// WhereParentCompanyBy keeps only Studio records that have a parentCompany
// edge whose target node matches the filter composed inside build — a typed
// CountryQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereParentCompany: no
// hand-written DQL or $N placeholders.
func (q *StudioQuery) WhereParentCompanyBy(build func(*CountryQuery)) *StudioQuery {
	sub := &CountryQuery{typed: typed.NewDetachedQuery[schema.Country]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("parentCompany", expr, params...)
	}
	return q
}

// WhereFilms keeps only Studio records that have a films
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *StudioQuery) WhereFilms(filter string, params ...any) *StudioQuery {
	q.typed.WhereEdge("films", filter, params...)
	return q
}

// WhereFilmsBy keeps only Studio records that have a films
// edge whose target node matches the filter composed inside build — a typed
// FilmQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereFilms: no
// hand-written DQL or $N placeholders.
func (q *StudioQuery) WhereFilmsBy(build func(*FilmQuery)) *StudioQuery {
	sub := &FilmQuery{typed: typed.NewDetachedQuery[schema.Film]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("films", expr, params...)
	}
	return q
}

// WhereAdvisors keeps only Studio records that have a advisors
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *StudioQuery) WhereAdvisors(filter string, params ...any) *StudioQuery {
	q.typed.WhereEdge("advisors", filter, params...)
	return q
}

// WhereAdvisorsBy keeps only Studio records that have a advisors
// edge whose target node matches the filter composed inside build — a typed
// DirectorQuery on which By<Field>/Or calls accumulate (ANDing, with Or
// for alternatives). It is the type-safe form of WhereAdvisors: no
// hand-written DQL or $N placeholders.
func (q *StudioQuery) WhereAdvisorsBy(build func(*DirectorQuery)) *StudioQuery {
	sub := &DirectorQuery{typed: typed.NewDetachedQuery[schema.Director]()}
	build(sub)
	if expr, params := sub.typed.CombinedFilter(); expr != "" {
		q.typed.WhereEdge("advisors", expr, params...)
	}
	return q
}

// ByName keeps only Studio records whose name matches one
// of filters. Terms within filters join with OR. Negated filters (Negated:true) become
// NOT eq(...). An empty filters slice is a no-op.
func (q *StudioQuery) ByName(filters ...filter.String) *StudioQuery {
	var b filter.Builder
	b.EqGroupString("name", filters)
	if expr, params := b.Build(); expr != "" {
		q.typed.Filter(expr, params...)
	}
	return q
}

// Or keeps only Studio records matching at least one of builders. Each builder
// receives a fresh StudioQuery whose By<Field>/Filter calls accumulate (ANDing
// within the builder); the builders' filters are ORed together and the whole
// group ANDs with the rest of the query. Builders that add no filter are
// skipped; an empty Or is a no-op.
func (q *StudioQuery) Or(builders ...func(*StudioQuery)) *StudioQuery {
	subs := make([]*typed.Query[schema.Studio], 0, len(builders))
	for _, build := range builders {
		sub := &StudioQuery{typed: typed.NewDetachedQuery[schema.Studio]()}
		build(sub)
		subs = append(subs, sub.typed)
	}
	q.typed.OrGroup(subs...)
	return q
}

// Nodes executes the query and returns the Studio entities.
func (q *StudioQuery) Nodes() ([]*Studio, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Studio, len(recs))
	for i := range recs {
		out[i] = NewStudioWithRecord(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// Studio entity, or nil if no rows matched.
func (q *StudioQuery) First() (*Studio, error) {
	r, err := q.typed.First()
	if err != nil || r == nil {
		return nil, err
	}
	return NewStudioWithRecord(r), nil
}

// IterNodes streams the query's results as Studio entities, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *StudioQuery) IterNodes() iter.Seq2[*Studio, error] {
	return func(yield func(*Studio, error) bool) {
		for r, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(NewStudioWithRecord(r), nil) {
				return
			}
		}
	}
}
